server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/v1/auth/**

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - TokenValidatorFilter

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/v1/event-groups/**
          filters:
            - TokenValidatorFilter

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/v1/events/**
          filters:
            - TokenValidatorFilter

        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/v1/registrations/**
          filters:
            - TokenValidatorFilter

        - id: poll-service
          uri: lb://poll-service
          predicates:
            - Path=/api/v1/polls/**
          filters:
            - TokenValidatorFilter

        - id: poll-service
          uri: lb://poll-service
          predicates:
            - Path=/pollWS/**
          filters:
            - TokenValidatorFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8079/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
