server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8079/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: security-service

  datasource:
    url: jdbc:mariadb://localhost/security_database
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    baseline-on-migrate: true
    out-of-order: true
    baseline-version: 0
    locations:
      - classpath:/db/migration

application:
  security-props:
    introspection-uri: https://idp.uni-plovdiv.bg/jans-auth/restv1/introspection
    introspection-client-id: 7193a5c7-71e4-45c2-adb1-7acd2deca515
    introspection-client-secret: 562825d5-5381-4b15-8b23-452e8c71b230
    user-info-endpoint: https://idp.uni-plovdiv.bg/jans-auth/restv1/userinfo
  kafka:
    bootstrap-servers: localhost:9092
    consumer-group-id: event-service
    retry-back-off-interval-ms: 2000
    retry-max-attempts: 5
    dlq-topic-name: security-service-dlq
  user-details-request-topic: user-details-request
  user-details-response-topic: user-details-response
